exclude: iqe_vulnerability_api
repos:
- repo: https://github.com/asottile/reorder_python_imports
  rev: v2.7.1
  hooks:
  - id: reorder-python-imports
    language_version: python3
- repo: https://github.com/ambv/black
  rev: 22.1.0
  hooks:
  - id: black
    args: [--safe, --quiet, --line-length, "100"]
    language_version: python3
    require_serial: true
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: trailing-whitespace
    language_version: python3
  - id: end-of-file-fixer
    language_version: python3
  - id: check-yaml
    language_version: python3
  - id: debug-statements
    language_version: python3
- repo: https://gitlab.com/pycqa/flake8.git
  rev: 3.9.2
  hooks:
  - id: flake8
    language_version: python3
- repo: https://gitlab.cee.redhat.com/insights-qe/iqe-metadata-linting
  rev: v22.02.04.0
  hooks:
  - id: iqe-metadata-linting
    language_version: python3
- repo: https://github.com/asottile/pyupgrade
  rev: v2.31.0
  hooks:
  - id: pyupgrade
    language_version: python3
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.931
  hooks:
  - id: mypy
    additional_dependencies: [types-all, types-attrs]
- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types:
        - python
      args:
        - -j
        - '0'
      require_serial: true
